### ISSUE TITLE
Uglify failing with latest version

### ISSUE THREAD

**Issue by ZawNaing** [NativeScript/nativescript-sdk-examples-ng#347] opened 2018-12-26 04:37 UTC
Hi there,
   After cloning the repo from Github, can't run with webpack.
tns run ios --bundle --env.uglify. It's ok when running with tns run ios.
How can I configure to accept in webpack?
<img width="2042" alt="screen shot 2018-12-26 at 11 06 41 am" src="https://user-images.githubusercontent.com/22611029/50432169-5eff0f00-08fe-11e9-89d6-8917988bd625.png">

**Comment by NickIliev** [comment] 2018-12-26 09:50
@ZawNaing thank you for reporting this issue - we will investigate the reasons and post the solution here.

meanwhile, to build the application you can skip the uglify flag
```
tns run android --bundle
```

Marking this one as a bug as it seems that uglification is not passing with the current `master` branch (and also with [the updated branch)](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/348).

**Comment by dtopuzov** [comment] 2018-12-28 19:17
May be related to https://github.com/NativeScript/nativescript-angular/issues/1572

**Comment by NickIliev** [comment] 2019-04-22 10:30
Closing as the issue is not reproducible with the latest versions

**Closed by NickIliev** 2019-04-22 10:30 UTC
Labels: bug
